//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalAppCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public int EmployerId { get; set; }
        public string EmployerName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
